### ISSUE TITLE
Sometimes raises RuntimeError("cannot join current thread")

### ISSUE THREAD

**Issue by ramonz** [eandersson/amqpstorm#11]
Hi. I use your library (ver 1.2.7) in several projects and it works well. But some of this projects rarely prints exception traceback in a log:
```
Exception in thread amqpstorm.io:
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/io.py", line 221, in _process_incoming_data
    self.buffer = self.on_read(self.buffer)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/connection.py", line 246, in _read_buffer
    self._channel0.on_frame(frame_in)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/channel0.py", line 40, in on_frame
    self._write_frame(Heartbeat())
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/channel0.py", line 104, in _write_frame
    self._connection.write_frame(0, frame_out)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/connection.py", line 177, in write_frame
    self.io.write_to_socket(frame_data)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/io.py", line 133, in write_to_socket
    self.on_error(why)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/connection.py", line 289, in _handle_socket_error
    self.close()
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/connection.py", line 134, in close
    self.io.close()
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/site-packages/amqpstorm/io.py", line 104, in close
    self.inbound_thread.join(timeout=1)
  File "/home/user/.pyenv/versions/2.7.10/lib/python2.7/threading.py", line 940, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread
```
I can't reproduce this error by hand but it still occurs. What are reasons of this behavior? Any suggestions? Thanks

**Comment by eandersson** [comment]
Hey,

Thanks for reporting this. This is actually a know issue, what happens is that when it is trying to close the connection it will join the process thread, but depending on what happens, the process thread is the one that actually handles the shutdown process, and is trying to join itself.

This should be handled gracefully though, so at least based on my testing this should not have any impact, and only happens when the connection is being terminated due to a socket issue.

I have a new build ready that will solve this, but due to the amount of changes I am going to wait a few weeks until I deploy it. If you have time feel free to install and test it.
https://github.com/eandersson/amqp-storm/commit/09290e5cdf6913f3db488175343dcdb2db329969

It currently contains some breaking changes, so you may need to update your code.
    - channel.start_consuming now defaults to to_tuple => False
    - channel.process_data_events now defaults to to_tuple => False
    - channel.basic.get now defaults to to_dict => False

I haven't made a decision on this change yet.

**Comment by ramonz** [comment]
i got it. thanks. 
probably i'll wait for the release

**Comment by eandersson** [comment]
I pushed the new version that should fix this. I added a lot of additional unit-test coverage, so hopefully you won't run into any new issues! Let me know!

**Comment by ramonz** [comment]
Okay. I updated today the library. I'll let you know if something goes wrong

**Comment by eandersson** [comment]
I haven't been able to re-create this since the patch, but if you encounter any new issues, please re-open the issue!
