### ISSUE TITLE
Jython 2.7.0 crashing with error

### ISSUE THREAD

**Issue by eandersson** [eandersson/amqpstorm#25]
```
DEBUG:amqpstorm.connection:Connection Opening
Traceback (most recent call last):
  File "C:/Users/eandersson/Documents/GitHub/amqp-storm/examples/simple_publisher.py", line 29, in <module>
    publisher()
  File "C:/Users/eandersson/Documents/GitHub/amqp-storm/examples/simple_publisher.py", line 0, in publisher
  File "C:\Users\eandersson\Documents\GitHub\amqp-storm\amqpstorm\connection.py", line 69, in __init__
    self.open()
  File "C:\Users\eandersson\Documents\GitHub\amqp-storm\amqpstorm\connection.py", line 174, in open
    self._io.open()
  File "C:\Users\eandersson\Documents\GitHub\amqp-storm\amqpstorm\io.py", line 98, in open
    self.socket = self._find_address_and_connect(sock_addresses)
  File "C:\Users\eandersson\Documents\GitHub\amqp-storm\amqpstorm\io.py", line 160, in _find_address_and_connect
    sock = self._create_socket(socket_family=address[0])
  File "C:\Users\eandersson\Documents\GitHub\amqp-storm\amqpstorm\io.py", line 177, in _create_socket
    sock.setsockopt(socket.SOL_TCP, socket.TCP_NODELAY, 1)
AttributeError: 'module' object has no attribute 'SOL_TCP'
```

**Comment by eandersson** [comment]
6cc881ce01c63e0a9075214f8fbcb9da443805a3
