### ISSUE TITLE
Testing with pamqp 3.0.0a4

### ISSUE THREAD

**Issue by gmr** [eandersson/amqpstorm#78]
I plan on releasing pamqp 3.0 soon and wanted to make sure you were aware of the changes that are making it into 3.0 and give you an opportunity to report any issues prior to its release.

Please see the version history @ https://pamqp.readthedocs.io/en/latest/history.html

**Comment by eandersson** [comment]
Thanks for the headsup @gmr. 

I have a test branch here testing the alphas.
https://github.com/eandersson/amqpstorm/commits/feature/pamqp3

I'll try it out again this weekend.

**Comment by eandersson** [comment]
btw added you as a collaborator. In case you ever need something to test pamqp changes against.

**Comment by gmr** [comment]
Thanks, this should be fixed now.

**Comment by eandersson** [comment]
Going to look into this tonight. Looks like `commands.Connection.Close()` causes an issue.

```
======================================================================
ERROR: test_functional_publish_1k_with_ssl (amqpstorm.tests.functional.ssl.reliability_tests.PublishAndConsume1kWithSSLTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/eandersson/amqpstorm/amqpstorm/tests/utility.py", line 284, in setup_wrapper
    self.connection.close()
  File "/home/travis/build/eandersson/amqpstorm/amqpstorm/connection.py", line 202, in close
    self._channel0.send_close_connection()
  File "/home/travis/build/eandersson/amqpstorm/amqpstorm/channel0.py", line 67, in send_close_connection
    self._write_frame(commands.Connection.Close())
  File "/home/travis/build/eandersson/amqpstorm/amqpstorm/channel0.py", line 215, in _write_frame
    self._connection.write_frame(0, frame_out)
  File "/home/travis/build/eandersson/amqpstorm/amqpstorm/connection.py", line 237, in write_frame
    frame_data = pamqp_frame.marshal(frame_out, channel_id)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pamqp/frame.py", line 37, in marshal
    return _marshal_method_frame(frame_value, channel_id)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pamqp/frame.py", line 122, in _marshal_method_frame
    common.Struct.integer.pack(value.index) + value.marshal())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pamqp/base.py", line 99, in marshal
    output.append(encode.by_type(data_value, data_type))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pamqp/encode.py", line 47, in by_type
    return METHODS[str(data_type)](value)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pamqp/encode.py", line 222, in short_uint
    raise TypeError('int required, received {}'.format(type(value)))
TypeError: int required, received <class 'NoneType'>
```

**Comment by gmr** [comment]
That's because class_id and method_id are not defaulted. Will check to ensure that's the "correct" behavior per the spec/xml.

**Comment by gmr** [comment]
So in the extended XML from RabbitMQ, class-id and method-id are domains, but have no defaults. I can add defaults to my own extended XML definitions. Looking to see what the previous behavior was.

**Comment by gmr** [comment]
v2 branch had defaults - https://github.com/gmr/pamqp/blob/2.3.0/pamqp/specification.py#L919

In the new codegen I only specify defaults when there are defaults called out in the spec, or if it's a deprecated field that must be a certain value.

What do you think the right behavior is here? I'm curious for @dzen's thoughts as well.

**Comment by eandersson** [comment]
If it is required it shouldn't be an optional variable imo.

**Comment by gmr** [comment]
Agreed - will look into what modifications need to be made to make it explicit, probably overriding the spec.

**Comment by eandersson** [comment]
After merging https://github.com/gmr/pamqp/pull/29 I now have the first green build.
https://travis-ci.org/github/eandersson/amqpstorm/builds/715387736
